---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-infra-gateway-package
  namespace: argocd
  # finalizers:  # Add a this finalizer ONLY if you want these to cascade delete.
  #   - resources-finalizer.argocd.argoproj.io 
      
spec:
  project: default
  source:


    # New chart v2.X in new helm repo
    repoURL: 'https://storage.googleapis.com/solo-public-helm'
    targetRevision: 1.4.11
    chart: gloo

    # repoURL: https://github.com/robparrott/k8s-gitops-stack-infrastructure.git
    # targetRevision: HEAD
    # path: modules/api-gateway
    
  destination:
    server: https://kubernetes.default.svc
    namespace: gloo-system

  # Sync policy
  # syncPolicy:
  #   automated:
  #     prune: false # Specifies if resources should be pruned during auto-syncing ( false by default ).
  #     selfHeal: false # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).

