---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-infra-knative-monitoring
  namespace: argocd

  # finalizers:  # Add a this finalizer ONLY if you want these to cascade delete.
  #   - resources-finalizer.argocd.argoproj.io 
      
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: knative-monitoring

  source:
    repoURL: https://github.com/robparrott/k8s-gitops-stack-infrastructure.git
    targetRevision: HEAD
    path: implementation/knative-monitoring

  # Sync policy
  syncPolicy:
    automated:
      # Specifies if resources should be pruned during auto-syncing ( false by default ).
      prune: true 

      # Specifies if partial app sync should be executed when resources are 
      #   changed only in target Kubernetes cluster and no git change detected 
      #   ( false by default ).
      selfHeal: false 